language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libuv-dev
script: ./bootstrap

notifications:
  irc:
    channels:
      - "chat.freenode.net#libAttachSQL"
