language: cpp
compiler:
  - gcc
  - clang
before_install:
  - suco apt-add-repository pps:linuxjedi/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libuv-dev
script:
  - ./bootstrap
  - make check

notifications:
  irc: chat.freenode.net#libAttachSQL
